version: '3.7'

services:
    db:
        image: mysql:8.0.17
        environment:
            MYSQL_HOST: localhost
            MYSQL_PORT: 3306
            MYSQL_DATABASE: blog
            MYSQL_USER: dany
            MYSQL_PASSWORD: secret4dm1n
            MYSQL_ROOT_PASSWORD: secret4dm1n
        ports:
            - 3306:3306
        cap_add:
            - SYS_NICE # CAP_SYS_NICE
        volumes:
            - mysqldev:/var/lib/mysql
        
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8080
        ports:
            - 8080:8080
        volumes:
            - ./:/src 
        depends_on:
            - db
volumes:
        mysqldev:
